"""Cloudflare R2 audio storage.

Audio files generated by AudioProducerAgent are kept on local disk under
backend/outputs/{session_id}/ AND uploaded to the configured R2 bucket.
The frontend prefers the public URL when present; if R2 is disabled or
an upload fails, the local file is still served via FastAPI as a fallback.

Public API:
    upload_audio(local_path, key, content_type)  -> public_url | None
    delete_audio(key)                            -> bool
    bucket_usage()                               -> {total_bytes, object_count}
"""

from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Any

from backend.config import (
    R2_ACCOUNT_ID,
    R2_ACCESS_KEY,
    R2_SECRET_KEY,
    R2_BUCKET,
    R2_PUBLIC_BASE_URL,
    R2_ENABLED,
)

logger = logging.getLogger(__name__)

_client: Any = None
_client_lock = threading.Lock()


def _get_client():
    """Return a memoised boto3 S3 client pointed at R2. Returns None if disabled."""
    global _client
    if not R2_ENABLED:
        return None
    if _client is not None:
        return _client
    with _client_lock:
        if _client is not None:
            return _client
        try:
            import boto3
            from botocore.config import Config
            _client = boto3.client(
                "s3",
                endpoint_url=f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
                aws_access_key_id=R2_ACCESS_KEY,
                aws_secret_access_key=R2_SECRET_KEY,
                # R2 is region-agnostic but boto3 requires a value
                region_name="auto",
                config=Config(
                    signature_version="s3v4",
                    retries={"max_attempts": 3, "mode": "standard"},
                ),
            )
            logger.info("R2 storage client initialised (bucket=%s)", R2_BUCKET)
        except Exception as e:
            logger.error("Failed to initialise R2 client: %s", e)
            _client = None
    return _client


def _content_type_for(path: Path) -> str:
    ext = path.suffix.lower()
    if ext == ".mp3":
        return "audio/mpeg"
    if ext == ".wav":
        return "audio/wav"
    return "application/octet-stream"


def upload_audio(local_path: Path, key: str, content_type: str | None = None) -> str | None:
    """Upload a file to R2. Returns the public URL on success, None on any failure.

    Failures are logged but never raised — callers should treat None as
    "R2 not used for this file; fall back to local serve".
    """
    if not R2_ENABLED:
        return None
    client = _get_client()
    if client is None:
        return None

    try:
        ct = content_type or _content_type_for(local_path)
        with open(local_path, "rb") as f:
            client.upload_fileobj(
                f,
                R2_BUCKET,
                key,
                ExtraArgs={
                    "ContentType": ct,
                    "CacheControl": "public, max-age=86400, immutable",
                },
            )
        url = f"{R2_PUBLIC_BASE_URL}/{key}"
        logger.debug("R2 upload OK: %s -> %s", local_path.name, key)
        return url
    except Exception as e:
        logger.warning("R2 upload failed for %s (%s): %s", local_path, key, e)
        return None


def delete_audio(key: str) -> bool:
    """Delete a single object. Safe to call when R2 is disabled."""
    if not R2_ENABLED:
        return False
    client = _get_client()
    if client is None:
        return False
    try:
        client.delete_object(Bucket=R2_BUCKET, Key=key)
        return True
    except Exception as e:
        logger.warning("R2 delete failed for %s: %s", key, e)
        return False


async def periodic_usage_check(
    interval_seconds: int = 3600,
    warn_threshold_gb: float = 8.0,
    crit_threshold_gb: float = 9.5,
) -> None:
    """Run forever, logging R2 bucket usage at fixed intervals.

    Logs INFO under threshold, WARNING at >= warn_threshold_gb, ERROR at
    >= crit_threshold_gb. Boto3 calls run in a thread so they don't block
    the event loop.
    """
    if not R2_ENABLED:
        return
    import asyncio
    while True:
        try:
            usage = await asyncio.to_thread(bucket_usage)
            if usage.get("enabled") and "total_gb" in usage:
                gb = float(usage["total_gb"])
                count = int(usage["object_count"])
                pct = float(usage.get("free_tier_used_percent", 0))
                if gb >= crit_threshold_gb:
                    logger.error(
                        "R2 CRITICAL: %.2f GB / 10 GB (%.1f%%) — %d objects. Approaching free-tier cap.",
                        gb, pct, count,
                    )
                elif gb >= warn_threshold_gb:
                    logger.warning(
                        "R2 WARNING: %.2f GB / 10 GB (%.1f%%) — %d objects. Consider cleanup.",
                        gb, pct, count,
                    )
                else:
                    logger.info(
                        "R2 usage: %.2f GB / 10 GB (%.1f%%) — %d objects.",
                        gb, pct, count,
                    )
        except Exception as e:
            logger.warning("R2 periodic usage check failed: %s", e)
        await asyncio.sleep(max(60, interval_seconds))


def bucket_usage() -> dict[str, Any]:
    """List the bucket and return total bytes + object count.

    Used by the admin usage endpoint. Paginates via list_objects_v2.
    """
    if not R2_ENABLED:
        return {"enabled": False}
    client = _get_client()
    if client is None:
        return {"enabled": False, "error": "client init failed"}

    total_bytes = 0
    total_count = 0
    try:
        paginator = client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=R2_BUCKET):
            for obj in page.get("Contents", []) or []:
                total_bytes += int(obj.get("Size") or 0)
                total_count += 1
        return {
            "enabled": True,
            "bucket": R2_BUCKET,
            "total_bytes": total_bytes,
            "total_mb": round(total_bytes / (1024 * 1024), 2),
            "total_gb": round(total_bytes / (1024 ** 3), 3),
            "object_count": total_count,
            "free_tier_gb": 10,
            "free_tier_used_percent": round(total_bytes / (10 * 1024 ** 3) * 100, 1),
        }
    except Exception as e:
        logger.error("R2 bucket_usage failed: %s", e)
        return {"enabled": True, "error": str(e)}
